[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["lms*"]

[project]
name = "PyLibMS"
version = "4.2.2"
requires-python = ">=3.10"
description = "Python library built for the libMessageStudio (LMS) proprietary file formats from Nintendo. Supports MSBT, MSBP, and MSBF."
readme = "README.md"
authors = [{ name = "AbdyyEee" }]
keywords = [
    "nintendo",
    "msbt",
    "message text",
    "msbp",
    "message project",
    "msbf",
    "message flowchart",
    "flw3",
    "modding",
    "libmessagestudio"]
license = "MIT"
license-files = ["LICENSE*"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "PyYAML>=6.0.1",
    "requests>=2.34.0"
]

[project.urls]
Documentation = "https://github.com/AbdyyEee/PylibMS/wiki"
Repository = "https://github.com/AbdyyEee/PylibMS"
