class LMS_Error(Exception): ...


class LMS_UnexpectedMagicError(Exception): ...


class LMS_MisalignedSizeError(Exception): ...


class LMS_UnsupportedSectionError(Exception): ...


class LMS_UnsupportedFileVersionError(Exception): ...
